# Generated by Django 5.0.1 on 2024-01-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.project'),
        ),
    ]
