# Generated by Django 5.0.1 on 2024-01-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectfile_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='attachment',
            field=models.FileField(upload_to='km/uploads/project/<django.db.models.fields.UUIDField>/files/'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(default='x', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.project'),
        ),
    ]
