# Generated by Django 5.0.1 on 2024-01-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectfile_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='attachment',
            field=models.FileField(upload_to='km/uploads/project/files/%Y/%m/%d/'),
        ),
    ]
