# Generated by Django 5.0.1 on 2024-01-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectnote',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='project.project'),
        ),
    ]
